#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/aliases.php';

use yii\console\Application;

$config = require __DIR__ . '/console/config/main.php';

try {
    exit(
    (new Application($config))
        ->run()
    );
} catch (Exception $e) {
    echo $e->getMessage();
}
